<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="programmes" nsURI="platform:/plugin/no.tdt4250.model/model/programmes.ecore"
    nsPrefix="programmes">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="thttp://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" eType="#//Course"
        eOpposite="#//Course/department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Instructor" eOpposite="#//Instructor/department"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" eType="#//Department"
        containment="true" eOpposite="#//Department/courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructor" eType="#//Instructor"
        eOpposite="#//Instructor/lecturedCourses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yearReference" upperBound="-1"
        eType="#//YearCourseReference" eOpposite="#//YearCourseReference/course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instructor" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturedCourses" upperBound="-1"
        eType="#//Course" eOpposite="#//Course/instructor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" eType="#//Department"
        eOpposite="#//Department/employees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializations" upperBound="-1"
        eType="#//Specialization" eOpposite="#//Specialization/specializesIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmeYears" upperBound="-1"
        eType="#//ProgrammeYear" eOpposite="#//ProgrammeYear/programme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinedCourseConstrains"
        upperBound="-1" eType="#//CombinedCourseConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ESemester">
    <eLiterals name="Autumn"/>
    <eLiterals name="Spring" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization" eSuperTypes="#//Programme">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializesIn" eType="#//Programme"
        containment="true" eOpposite="#//Programme/specializations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chosenIn" lowerBound="1"
        eType="#//ProgrammeYear"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgrammeYear">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programme" lowerBound="1"
        eType="#//Programme" eOpposite="#//Programme/programmeYears"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseReferences" upperBound="-1"
        eType="#//YearCourseReference" eOpposite="#//YearCourseReference/programmeYear"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearInProgramme" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YearCourseReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmeYear" lowerBound="1"
        eType="#//ProgrammeYear" eOpposite="#//ProgrammeYear/courseReferences"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course" eOpposite="#//Course/yearReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterType" eType="#//ESemester"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" lowerBound="1"
        eType="#//SemesterCourseConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemesterCourseConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgrammeCourseGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryCourseConstraint" eSuperTypes="#//SemesterCourseConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElectiveCourseConstraint" eSuperTypes="#//SemesterCourseConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="AmountCourseOutGroupConstraint" eSuperTypes="#//CombinedCourseConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amountOfCourses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroup" lowerBound="1"
        eType="#//ProgrammeCourseGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedCourseConstraint" eSuperTypes="#//SemesterCourseConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enrolledIn" eType="#//Programme"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="studentNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examAttempts" upperBound="-1"
        eType="#//ExamAttempt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExamAttempt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semester" eType="#//ESemester"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmeYear" eType="#//ProgrammeYear"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grade" eType="#//EGrade"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EGrade">
    <eLiterals name="A" literal="A"/>
    <eLiterals name="B" value="1" literal="B"/>
    <eLiterals name="C" value="2" literal="C"/>
    <eLiterals name="D" value="3" literal="D"/>
    <eLiterals name="E" value="4" literal="E"/>
    <eLiterals name="F" value="5" literal="F"/>
  </eClassifiers>
</ecore:EPackage>
